/**:
  ros__parameters:
    video_device: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:4:1.0-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "right_camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "right_cam"
