velodyne_driver_node:
  ros__parameters:
    device_ip: 192.168.1.201
    gps_time: false
    time_offset: 0.0
    enabled: true
    read_once: false
    read_fast: false
    repeat_delay: 0.0
    frame_id: velodyne
    model: VLP16
    rpm: 600.0
    port: 2368

velodyne_convert_node:
  ros__parameters:
    calibration: VLP16db.yaml
    min_range: 0.9
    max_range: 130.0
    view_direction: 0.0
    organize_cloud: true

velodyne_transform_node:
  ros__parameters:
    calibration: VLP16db.yaml
    min_range: 0.9
    max_range: 130.0
    view_direction: 0.0
    organize_cloud: true
velodyne_laserscan_node:
  ros__parameters:
    ring: -1
    resolution: 0.007

center_usb_cam_node:
  ros__parameters:
    video_device: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:11:1.0-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "center_camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "center_cam"

left_usb_cam_node:
  ros__parameters:
    video_device: "/dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_FE705E1F-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "left_camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "left_cam"

right_usb_cam_node:
  ros__parameters:
    video_device: "/dev/v4l/by-path/pci-0000:00:14.0-usb-0:4:1.0-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "right_camera"
    pixel_format: "yuyv"
    image_width: 640
    image_height: 480
    camera_name: "right_cam"

front_left_urg_node:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    ip_port: 10940
    serial_port: "/dev/serial/by-path/pci-0000:02:00.0-usb-0:3:1.0"
    serial_baud: 115200
    laser_frame_id: "laser_front_left"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: false
    publish_multiecho: false
    cluster: 1
    skip: 0

front_right_urg_node:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    ip_port: 10940
    serial_port: "/dev/serial/by-path/pci-0000:02:00.0-usb-0:2.4:1.0"
    serial_baud: 115200
    laser_frame_id: "laser_front_right"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: false
    publish_multiecho: false
    cluster: 1
    skip: 0

rear_urg_node:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    ip_port: 10940
    serial_port: "/dev/serial/by-path/pci-0000:02:00.0-usb-0:4:1.0"
    serial_baud: 115200
    laser_frame_id: "laser_rear"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: false
    publish_multiecho: false
    cluster: 1
    skip: 0
