bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /localization/pose_twist_fusion_filter/ekf_odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_through_poses_bt_xml: /home/tsukutsuku/tsukutsuku_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_through_poses_tsukutsuku.xml
    default_nav_to_pose_bt_xml: /home/tsukutsuku/tsukutsuku_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_to_pose_tsukutsuku.xml
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
        #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 6.3
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.4
      max_vel_y: 1.4
      max_vel_theta: 0.5
      min_speed_xy: 0.0
      max_speed_xy: 1.0
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 0.75
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -1.0
      decel_lim_y: 0.0
      decel_lim_theta: -1.0
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "ObstacleFootprint", "PathAlign", "PathDist", "GoalAlign", "GoalDist"]
      BaseObstacle.scale: 0.01
      BaseObstacle.sum_scores: false
      ObstacleFootprint.scale: 0.005 
      ObstacleFootprint.sum_scores: false
      PathAlign.scale: 12.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 24.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      # PreferForward.scale: 32.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0 #Hz
      publish_frequency: 10.0 #Hz
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 10
      height: 10
      lethal_cost_threshold: 65
      resolution: 0.05
      footprint: '[ [0.9, 0.33], [-0.2, 0.33], [-0.2, -0.33], [0.9, -0.33] ]'
      footprint_padding: 0.03
      # robot_radius: 0.9
      plugins: ["inflation_layer", "stvl_layer", "obstacle_layer"]
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 0.2
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        max_obstacle_height: 1.5
        unknown_threshold: 15 #what is?
        mark_threshold: 0 #what is?
        update_footprint_enabled: true
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.2
        mapping_mode: false
        map_save_duration: 60.0
        observation_sources: velodyne
        velodyne:
          topic: /sensing/velodyne_lower/no_ground/pointcloud
          marking: true
          clearing: true
          obstacle_range: 10.0
          min_obstacle_height: 0.3
          max_obstacle_height: 1.5
          expected_update_rate: 10.0
          observation_persistence: 0.0
          inf_is_valid: false
          voxel_filter: false
          clear_after_reading: true
          # max_z: 7.0
          # min_z: 0.1
          # vertical_fov_angle: 0.8745
          # horizontal_fov_angle: 1.048
          decay_acceleration: 15.0
          model_type: 1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: front_left_urg rear_urg 
        front_left_urg:
          topic: /sensing/front_left_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        front_right_urg:
          topic: /sensing/front_right_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
        rear_urg:
          topic: /sensing/rear_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.4
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0
      publish_frequency: 3.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      footprint: '[ [0.9, 0.33], [-0.2, 0.33], [-0.2, -0.33], [0.9, -0.33] ]'
      footprint_padding: 0.03
      # robot_radius: 0.9
      resolution: 0.3
      track_unknown_space: true
      always_send_full_costmap: True
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.2
#      stvl_layer:
#        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
#        enabled: true
#        voxel_decay: 0.5
#        decay_model: 0
#        voxel_size: 0.05
#        track_unknown_space: true
#        max_obstacle_height: 1.5
#        unknown_threshold: 15
#        mark_threshold: 0
#        update_footprint_enabled: true
#        combination_method: 1
#        origin_z: 0.0
#        publish_voxel_map: true
#        transform_tolerance: 0.2
#        mapping_mode: false
#        map_save_duration: 60.0
#        observation_sources: velodyne
#        velodyne:
#          topic: /sensing/velodyne_lower/no_ground/pointcloud
#          marking: true
#          clearing: true
#          obstacle_range: 40.0
#          min_obstacle_height: 0.3
#          max_obstacle_height: 1.5
#          expected_update_rate: 10.0
#          observation_persistence: 0.0
#          inf_is_valid: false
#          voxel_filter: false
#          clear_after_reading: true
#          # max_z: 7.0
#          # min_z: 0.1
#          # vertical_fov_angle: 0.8745
#          # horizontal_fov_angle: 1.048
#          decay_acceleration: 15.0
#          model_type: 1
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        observation_sources: front_left_urg front_right_urg rear_urg 
        front_left_urg:
          topic: /sensing/front_left_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 30.0
          raytrace_min_range: 0.0
          obstacle_max_range: 30.0
          obstacle_min_range: 0.0
        front_right_urg:
          topic: /sensing/front_right_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 30.0
          raytrace_min_range: 0.0
          obstacle_max_range: 30.0
          obstacle_min_range: 0.0
        rear_urg:
          topic: /sensing/rear_urg/scan
          max_obstacle_height: 1.5
          clearing: True
          marking: True
          inf_is_valid: False
          data_type: "LaserScan"
          expected_update_rate: 40.0
          raytrace_max_range: 30.0
          raytrace_min_range: 0.0
          obstacle_max_range: 30.0
          obstacle_min_range: 0.0
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/tsukutsuku/data/maps/sb/map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 500.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 1.0
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["wait", "backup"]
    wait:
      plugin: "nav2_recoveries/Wait"
    backup:
      plugin: "nav2_recoveries/BackUp"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
    
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: False
      waypoint_pause_duration: 0
